//HintName: MDatorGenerated.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591 // missing XML doc on generated members

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using MDator;

[assembly: global::MDator.KnownRequestAttribute(typeof(global::Snap.UserCreated))]

namespace MDator.Generated.SnapshotTest
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Code Generated by MDator Source Generator")]
    internal static class MDatorGeneratedRegistration
    {
        [ModuleInitializer]
        internal static void Init()
        {
            global::MDator.MDatorGeneratedHook.Registrations.Add(Register);
        }

        private static void Register(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::MDator.MDatorConfiguration cfg)
        {
            var lt = cfg.Lifetime;
            // IMediator registered once per consuming assembly set; TryAdd to avoid duplicates when
            // multiple generated registrations run in the same composition root.
            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IMediator), typeof(GeneratedMediator), lt));
            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.ISender), static sp => sp.GetRequiredService<global::MDator.IMediator>(), lt));
            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAdd(services, new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.IPublisher), static sp => sp.GetRequiredService<global::MDator.IMediator>(), lt));

            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.INotificationHandler<global::Snap.UserCreated>), typeof(global::Snap.SendWelcomeMail), lt));
            services.Add(new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(global::MDator.INotificationHandler<global::Snap.UserCreated>), typeof(global::Snap.AuditUserCreated), lt));
        }
    }

    internal sealed class GeneratedMediator : global::MDator.IMediator
    {
        private readonly global::System.IServiceProvider _sp;
        private readonly global::MDator.MDatorConfiguration _cfg;
        private readonly global::MDator.INotificationPublisher _publisher;

        public GeneratedMediator(global::System.IServiceProvider sp, global::MDator.MDatorConfiguration cfg, global::MDator.INotificationPublisher publisher)
        {
            _sp = sp;
            _cfg = cfg;
            _publisher = publisher;
        }

        public global::System.Threading.Tasks.Task<TResponse> Send<TResponse>(global::MDator.IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)
        {
            switch (request)
            {
                default:
                    return SendUnknown<TResponse>(request, cancellationToken);
            }
        }

        private global::System.Threading.Tasks.Task<TResponse> SendUnknown<TResponse>(global::MDator.IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken)
        {
            return global::MDator.RuntimeDispatch.SendFallback<TResponse>(_sp, _cfg, request, cancellationToken);
        }

        public global::System.Threading.Tasks.Task Send<TRequest>(TRequest request, global::System.Threading.CancellationToken cancellationToken = default) where TRequest : global::MDator.IRequest
        {
            switch (request)
            {
                default:
                    return global::MDator.RuntimeDispatch.SendVoidFallback(_sp, _cfg, request, cancellationToken);
            }
        }

        public async global::System.Threading.Tasks.Task<object?> Send(object request, global::System.Threading.CancellationToken cancellationToken = default)
        {
            switch (request)
            {
                default:
                    return await global::MDator.RuntimeDispatch.SendObjectFallback(_sp, _cfg, request, cancellationToken).ConfigureAwait(false);
            }
        }

        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(global::MDator.IStreamRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)
        {
            switch (request)
            {
                default:
                    return global::MDator.RuntimeDispatch.StreamFallback<TResponse>(_sp, _cfg, request, cancellationToken);
            }
        }

        public global::System.Collections.Generic.IAsyncEnumerable<object?> CreateStream(object request, global::System.Threading.CancellationToken cancellationToken = default)
        {
            return global::MDator.RuntimeDispatch.StreamObjectFallback(_sp, _cfg, request, cancellationToken);
        }

        public global::System.Threading.Tasks.Task Publish<TNotification>(TNotification notification, global::System.Threading.CancellationToken cancellationToken = default) where TNotification : global::MDator.INotification
        {
            switch (notification)
            {
                case global::Snap.UserCreated __n_UserCreated:
                    return PublishCore_UserCreated(__n_UserCreated, cancellationToken);
                default:
                    return global::MDator.RuntimeDispatch.PublishFallback(_sp, _publisher, notification, cancellationToken);
            }
        }

        public global::System.Threading.Tasks.Task Publish(object notification, global::System.Threading.CancellationToken cancellationToken = default)
        {
            if (notification is null) throw new global::System.ArgumentNullException(nameof(notification));
            if (notification is not global::MDator.INotification __n_typed) throw new global::System.ArgumentException("MDator: Publish requires an INotification instance.", nameof(notification));
            switch (notification)
            {
                case global::Snap.UserCreated __n_UserCreated:
                    return PublishCore_UserCreated(__n_UserCreated, cancellationToken);
                default:
                    return global::MDator.RuntimeDispatch.PublishFallback(_sp, _publisher, __n_typed, cancellationToken);
            }
        }

        private global::System.Threading.Tasks.Task PublishCore_UserCreated(global::Snap.UserCreated notification, global::System.Threading.CancellationToken ct)
        {
            var __all = _sp.GetServices<global::MDator.INotificationHandler<global::Snap.UserCreated>>();
            var __list = new global::System.Collections.Generic.List<global::MDator.NotificationHandlerExecutor>();
            foreach (var __h in __all)
            {
                var __hCapture = __h;
                __list.Add(new global::MDator.NotificationHandlerExecutor(__hCapture, (__msg, __ct) => __hCapture.Handle((global::Snap.UserCreated)__msg, __ct)));
            }
            return _publisher.Publish(__list, notification, ct);
        }

    }
}
